🔧 Checking requirements...
✅ All required tools are installed

📦 Bootstrapping Linear environment...
✅ .linear/ directory initialized

🔐 Starting OAuth session...
🌐 Opening browser for authentication...
✅ OAuth code captured

🧪 Validating OAuth code...
✅ OAuth code is fresh (XX seconds old)

🔁 Exchanging code for access token...
✅ Access token acquired

🔐 Verifying token authentication...
✅ Token is authenticated and usable

📎 Verifying Linear issue context...
✅ Issue ID found: lin_123abc...

🔗 Linking issue (optional)...
⚠️ Skipping issue linking (already linked or not required)

📝 Posting content to Linear...
✅ Mutation dispatched

📬 Inspecting Linear API response...
✅ Response logged to .linear/api_response.json

📊 Checking session status...
✅ Session valid, token active, mutation confirmed
